// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: godchain/godbridge/v1/tx.proto

package msg

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type SourceEvidence struct {
	Height          uint64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	BlockHash       []byte `protobuf:"bytes,2,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	TransactionHash []byte `protobuf:"bytes,3,opt,name=transaction_hash,json=transactionHash,proto3" json:"transaction_hash,omitempty"`
	LogIndex        uint32 `protobuf:"varint,4,opt,name=log_index,json=logIndex,proto3" json:"log_index,omitempty"`
}

func (m *SourceEvidence) Reset()         { *m = SourceEvidence{} }
func (m *SourceEvidence) String() string { return proto.CompactTextString(m) }
func (*SourceEvidence) ProtoMessage()    {}
func (*SourceEvidence) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f9f64153a06c9c8, []int{0}
}
func (m *SourceEvidence) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SourceEvidence) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SourceEvidence.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SourceEvidence) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SourceEvidence.Merge(m, src)
}
func (m *SourceEvidence) XXX_Size() int {
	return m.Size()
}
func (m *SourceEvidence) XXX_DiscardUnknown() {
	xxx_messageInfo_SourceEvidence.DiscardUnknown(m)
}

var xxx_messageInfo_SourceEvidence proto.InternalMessageInfo

func (m *SourceEvidence) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *SourceEvidence) GetBlockHash() []byte {
	if m != nil {
		return m.BlockHash
	}
	return nil
}

func (m *SourceEvidence) GetTransactionHash() []byte {
	if m != nil {
		return m.TransactionHash
	}
	return nil
}

func (m *SourceEvidence) GetLogIndex() uint32 {
	if m != nil {
		return m.LogIndex
	}
	return 0
}

type MsgAcceptDeposit struct {
	// The outer signer pays GOD fees. The quorum separately authorizes release.
	Sender          string          `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	DepositSequence uint64          `protobuf:"varint,2,opt,name=deposit_sequence,json=depositSequence,proto3" json:"deposit_sequence,omitempty"`
	Recipient       string          `protobuf:"bytes,3,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Amount          string          `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Evidence        *SourceEvidence `protobuf:"bytes,5,opt,name=evidence,proto3" json:"evidence,omitempty"`
	Approvals       [][]byte        `protobuf:"bytes,6,rep,name=approvals,proto3" json:"approvals,omitempty"`
}

func (m *MsgAcceptDeposit) Reset()         { *m = MsgAcceptDeposit{} }
func (m *MsgAcceptDeposit) String() string { return proto.CompactTextString(m) }
func (*MsgAcceptDeposit) ProtoMessage()    {}
func (*MsgAcceptDeposit) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f9f64153a06c9c8, []int{1}
}
func (m *MsgAcceptDeposit) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAcceptDeposit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAcceptDeposit.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAcceptDeposit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAcceptDeposit.Merge(m, src)
}
func (m *MsgAcceptDeposit) XXX_Size() int {
	return m.Size()
}
func (m *MsgAcceptDeposit) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAcceptDeposit.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAcceptDeposit proto.InternalMessageInfo

func (m *MsgAcceptDeposit) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgAcceptDeposit) GetDepositSequence() uint64 {
	if m != nil {
		return m.DepositSequence
	}
	return 0
}

func (m *MsgAcceptDeposit) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

func (m *MsgAcceptDeposit) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *MsgAcceptDeposit) GetEvidence() *SourceEvidence {
	if m != nil {
		return m.Evidence
	}
	return nil
}

func (m *MsgAcceptDeposit) GetApprovals() [][]byte {
	if m != nil {
		return m.Approvals
	}
	return nil
}

type MsgAcceptDepositResponse struct {
}

func (m *MsgAcceptDepositResponse) Reset()         { *m = MsgAcceptDepositResponse{} }
func (m *MsgAcceptDepositResponse) String() string { return proto.CompactTextString(m) }
func (*MsgAcceptDepositResponse) ProtoMessage()    {}
func (*MsgAcceptDepositResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f9f64153a06c9c8, []int{2}
}
func (m *MsgAcceptDepositResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAcceptDepositResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAcceptDepositResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAcceptDepositResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAcceptDepositResponse.Merge(m, src)
}
func (m *MsgAcceptDepositResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgAcceptDepositResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAcceptDepositResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAcceptDepositResponse proto.InternalMessageInfo

type MsgRequestWithdrawal struct {
	Sender string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	// Raw 20-byte source-chain recipient; no populated address is supplied.
	SourceRecipient []byte `protobuf:"bytes,2,opt,name=source_recipient,json=sourceRecipient,proto3" json:"source_recipient,omitempty"`
	Amount          string `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *MsgRequestWithdrawal) Reset()         { *m = MsgRequestWithdrawal{} }
func (m *MsgRequestWithdrawal) String() string { return proto.CompactTextString(m) }
func (*MsgRequestWithdrawal) ProtoMessage()    {}
func (*MsgRequestWithdrawal) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f9f64153a06c9c8, []int{3}
}
func (m *MsgRequestWithdrawal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRequestWithdrawal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRequestWithdrawal.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRequestWithdrawal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRequestWithdrawal.Merge(m, src)
}
func (m *MsgRequestWithdrawal) XXX_Size() int {
	return m.Size()
}
func (m *MsgRequestWithdrawal) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRequestWithdrawal.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRequestWithdrawal proto.InternalMessageInfo

func (m *MsgRequestWithdrawal) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgRequestWithdrawal) GetSourceRecipient() []byte {
	if m != nil {
		return m.SourceRecipient
	}
	return nil
}

func (m *MsgRequestWithdrawal) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

type MsgRequestWithdrawalResponse struct {
	WithdrawalSequence uint64 `protobuf:"varint,1,opt,name=withdrawal_sequence,json=withdrawalSequence,proto3" json:"withdrawal_sequence,omitempty"`
	WithdrawalId       []byte `protobuf:"bytes,2,opt,name=withdrawal_id,json=withdrawalId,proto3" json:"withdrawal_id,omitempty"`
}

func (m *MsgRequestWithdrawalResponse) Reset()         { *m = MsgRequestWithdrawalResponse{} }
func (m *MsgRequestWithdrawalResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRequestWithdrawalResponse) ProtoMessage()    {}
func (*MsgRequestWithdrawalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f9f64153a06c9c8, []int{4}
}
func (m *MsgRequestWithdrawalResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRequestWithdrawalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRequestWithdrawalResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRequestWithdrawalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRequestWithdrawalResponse.Merge(m, src)
}
func (m *MsgRequestWithdrawalResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRequestWithdrawalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRequestWithdrawalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRequestWithdrawalResponse proto.InternalMessageInfo

func (m *MsgRequestWithdrawalResponse) GetWithdrawalSequence() uint64 {
	if m != nil {
		return m.WithdrawalSequence
	}
	return 0
}

func (m *MsgRequestWithdrawalResponse) GetWithdrawalId() []byte {
	if m != nil {
		return m.WithdrawalId
	}
	return nil
}

type MsgAuthorizeWithdrawal struct {
	Sender             string   `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	WithdrawalSequence uint64   `protobuf:"varint,2,opt,name=withdrawal_sequence,json=withdrawalSequence,proto3" json:"withdrawal_sequence,omitempty"`
	WithdrawalId       []byte   `protobuf:"bytes,3,opt,name=withdrawal_id,json=withdrawalId,proto3" json:"withdrawal_id,omitempty"`
	Approvals          [][]byte `protobuf:"bytes,4,rep,name=approvals,proto3" json:"approvals,omitempty"`
}

func (m *MsgAuthorizeWithdrawal) Reset()         { *m = MsgAuthorizeWithdrawal{} }
func (m *MsgAuthorizeWithdrawal) String() string { return proto.CompactTextString(m) }
func (*MsgAuthorizeWithdrawal) ProtoMessage()    {}
func (*MsgAuthorizeWithdrawal) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f9f64153a06c9c8, []int{5}
}
func (m *MsgAuthorizeWithdrawal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAuthorizeWithdrawal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAuthorizeWithdrawal.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAuthorizeWithdrawal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAuthorizeWithdrawal.Merge(m, src)
}
func (m *MsgAuthorizeWithdrawal) XXX_Size() int {
	return m.Size()
}
func (m *MsgAuthorizeWithdrawal) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAuthorizeWithdrawal.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAuthorizeWithdrawal proto.InternalMessageInfo

func (m *MsgAuthorizeWithdrawal) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgAuthorizeWithdrawal) GetWithdrawalSequence() uint64 {
	if m != nil {
		return m.WithdrawalSequence
	}
	return 0
}

func (m *MsgAuthorizeWithdrawal) GetWithdrawalId() []byte {
	if m != nil {
		return m.WithdrawalId
	}
	return nil
}

func (m *MsgAuthorizeWithdrawal) GetApprovals() [][]byte {
	if m != nil {
		return m.Approvals
	}
	return nil
}

type MsgAuthorizeWithdrawalResponse struct {
}

func (m *MsgAuthorizeWithdrawalResponse) Reset()         { *m = MsgAuthorizeWithdrawalResponse{} }
func (m *MsgAuthorizeWithdrawalResponse) String() string { return proto.CompactTextString(m) }
func (*MsgAuthorizeWithdrawalResponse) ProtoMessage()    {}
func (*MsgAuthorizeWithdrawalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f9f64153a06c9c8, []int{6}
}
func (m *MsgAuthorizeWithdrawalResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAuthorizeWithdrawalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAuthorizeWithdrawalResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAuthorizeWithdrawalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAuthorizeWithdrawalResponse.Merge(m, src)
}
func (m *MsgAuthorizeWithdrawalResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgAuthorizeWithdrawalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAuthorizeWithdrawalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAuthorizeWithdrawalResponse proto.InternalMessageInfo

type MsgResolvePayment struct {
	Sender             string          `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	WithdrawalSequence uint64          `protobuf:"varint,2,opt,name=withdrawal_sequence,json=withdrawalSequence,proto3" json:"withdrawal_sequence,omitempty"`
	WithdrawalId       []byte          `protobuf:"bytes,3,opt,name=withdrawal_id,json=withdrawalId,proto3" json:"withdrawal_id,omitempty"`
	Evidence           *SourceEvidence `protobuf:"bytes,4,opt,name=evidence,proto3" json:"evidence,omitempty"`
	Approvals          [][]byte        `protobuf:"bytes,5,rep,name=approvals,proto3" json:"approvals,omitempty"`
}

func (m *MsgResolvePayment) Reset()         { *m = MsgResolvePayment{} }
func (m *MsgResolvePayment) String() string { return proto.CompactTextString(m) }
func (*MsgResolvePayment) ProtoMessage()    {}
func (*MsgResolvePayment) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f9f64153a06c9c8, []int{7}
}
func (m *MsgResolvePayment) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgResolvePayment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgResolvePayment.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgResolvePayment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgResolvePayment.Merge(m, src)
}
func (m *MsgResolvePayment) XXX_Size() int {
	return m.Size()
}
func (m *MsgResolvePayment) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgResolvePayment.DiscardUnknown(m)
}

var xxx_messageInfo_MsgResolvePayment proto.InternalMessageInfo

func (m *MsgResolvePayment) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgResolvePayment) GetWithdrawalSequence() uint64 {
	if m != nil {
		return m.WithdrawalSequence
	}
	return 0
}

func (m *MsgResolvePayment) GetWithdrawalId() []byte {
	if m != nil {
		return m.WithdrawalId
	}
	return nil
}

func (m *MsgResolvePayment) GetEvidence() *SourceEvidence {
	if m != nil {
		return m.Evidence
	}
	return nil
}

func (m *MsgResolvePayment) GetApprovals() [][]byte {
	if m != nil {
		return m.Approvals
	}
	return nil
}

type MsgResolvePaymentResponse struct {
}

func (m *MsgResolvePaymentResponse) Reset()         { *m = MsgResolvePaymentResponse{} }
func (m *MsgResolvePaymentResponse) String() string { return proto.CompactTextString(m) }
func (*MsgResolvePaymentResponse) ProtoMessage()    {}
func (*MsgResolvePaymentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f9f64153a06c9c8, []int{8}
}
func (m *MsgResolvePaymentResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgResolvePaymentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgResolvePaymentResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgResolvePaymentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgResolvePaymentResponse.Merge(m, src)
}
func (m *MsgResolvePaymentResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgResolvePaymentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgResolvePaymentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgResolvePaymentResponse proto.InternalMessageInfo

type MsgCancelWithdrawal struct {
	Sender             string          `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	WithdrawalSequence uint64          `protobuf:"varint,2,opt,name=withdrawal_sequence,json=withdrawalSequence,proto3" json:"withdrawal_sequence,omitempty"`
	WithdrawalId       []byte          `protobuf:"bytes,3,opt,name=withdrawal_id,json=withdrawalId,proto3" json:"withdrawal_id,omitempty"`
	Evidence           *SourceEvidence `protobuf:"bytes,4,opt,name=evidence,proto3" json:"evidence,omitempty"`
	Approvals          [][]byte        `protobuf:"bytes,5,rep,name=approvals,proto3" json:"approvals,omitempty"`
}

func (m *MsgCancelWithdrawal) Reset()         { *m = MsgCancelWithdrawal{} }
func (m *MsgCancelWithdrawal) String() string { return proto.CompactTextString(m) }
func (*MsgCancelWithdrawal) ProtoMessage()    {}
func (*MsgCancelWithdrawal) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f9f64153a06c9c8, []int{9}
}
func (m *MsgCancelWithdrawal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCancelWithdrawal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCancelWithdrawal.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCancelWithdrawal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCancelWithdrawal.Merge(m, src)
}
func (m *MsgCancelWithdrawal) XXX_Size() int {
	return m.Size()
}
func (m *MsgCancelWithdrawal) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCancelWithdrawal.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCancelWithdrawal proto.InternalMessageInfo

func (m *MsgCancelWithdrawal) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgCancelWithdrawal) GetWithdrawalSequence() uint64 {
	if m != nil {
		return m.WithdrawalSequence
	}
	return 0
}

func (m *MsgCancelWithdrawal) GetWithdrawalId() []byte {
	if m != nil {
		return m.WithdrawalId
	}
	return nil
}

func (m *MsgCancelWithdrawal) GetEvidence() *SourceEvidence {
	if m != nil {
		return m.Evidence
	}
	return nil
}

func (m *MsgCancelWithdrawal) GetApprovals() [][]byte {
	if m != nil {
		return m.Approvals
	}
	return nil
}

type MsgCancelWithdrawalResponse struct {
}

func (m *MsgCancelWithdrawalResponse) Reset()         { *m = MsgCancelWithdrawalResponse{} }
func (m *MsgCancelWithdrawalResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCancelWithdrawalResponse) ProtoMessage()    {}
func (*MsgCancelWithdrawalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f9f64153a06c9c8, []int{10}
}
func (m *MsgCancelWithdrawalResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCancelWithdrawalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCancelWithdrawalResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCancelWithdrawalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCancelWithdrawalResponse.Merge(m, src)
}
func (m *MsgCancelWithdrawalResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCancelWithdrawalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCancelWithdrawalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCancelWithdrawalResponse proto.InternalMessageInfo

type MsgPauseBridge struct {
	Sender       string   `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	ControlNonce uint64   `protobuf:"varint,2,opt,name=control_nonce,json=controlNonce,proto3" json:"control_nonce,omitempty"`
	Intake       bool     `protobuf:"varint,3,opt,name=intake,proto3" json:"intake,omitempty"`
	Outflow      bool     `protobuf:"varint,4,opt,name=outflow,proto3" json:"outflow,omitempty"`
	Approvals    [][]byte `protobuf:"bytes,5,rep,name=approvals,proto3" json:"approvals,omitempty"`
}

func (m *MsgPauseBridge) Reset()         { *m = MsgPauseBridge{} }
func (m *MsgPauseBridge) String() string { return proto.CompactTextString(m) }
func (*MsgPauseBridge) ProtoMessage()    {}
func (*MsgPauseBridge) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f9f64153a06c9c8, []int{11}
}
func (m *MsgPauseBridge) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgPauseBridge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgPauseBridge.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgPauseBridge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgPauseBridge.Merge(m, src)
}
func (m *MsgPauseBridge) XXX_Size() int {
	return m.Size()
}
func (m *MsgPauseBridge) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgPauseBridge.DiscardUnknown(m)
}

var xxx_messageInfo_MsgPauseBridge proto.InternalMessageInfo

func (m *MsgPauseBridge) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgPauseBridge) GetControlNonce() uint64 {
	if m != nil {
		return m.ControlNonce
	}
	return 0
}

func (m *MsgPauseBridge) GetIntake() bool {
	if m != nil {
		return m.Intake
	}
	return false
}

func (m *MsgPauseBridge) GetOutflow() bool {
	if m != nil {
		return m.Outflow
	}
	return false
}

func (m *MsgPauseBridge) GetApprovals() [][]byte {
	if m != nil {
		return m.Approvals
	}
	return nil
}

type MsgPauseBridgeResponse struct {
}

func (m *MsgPauseBridgeResponse) Reset()         { *m = MsgPauseBridgeResponse{} }
func (m *MsgPauseBridgeResponse) String() string { return proto.CompactTextString(m) }
func (*MsgPauseBridgeResponse) ProtoMessage()    {}
func (*MsgPauseBridgeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f9f64153a06c9c8, []int{12}
}
func (m *MsgPauseBridgeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgPauseBridgeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgPauseBridgeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgPauseBridgeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgPauseBridgeResponse.Merge(m, src)
}
func (m *MsgPauseBridgeResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgPauseBridgeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgPauseBridgeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgPauseBridgeResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*SourceEvidence)(nil), "godchain.godbridge.v1.SourceEvidence")
	proto.RegisterType((*MsgAcceptDeposit)(nil), "godchain.godbridge.v1.MsgAcceptDeposit")
	proto.RegisterType((*MsgAcceptDepositResponse)(nil), "godchain.godbridge.v1.MsgAcceptDepositResponse")
	proto.RegisterType((*MsgRequestWithdrawal)(nil), "godchain.godbridge.v1.MsgRequestWithdrawal")
	proto.RegisterType((*MsgRequestWithdrawalResponse)(nil), "godchain.godbridge.v1.MsgRequestWithdrawalResponse")
	proto.RegisterType((*MsgAuthorizeWithdrawal)(nil), "godchain.godbridge.v1.MsgAuthorizeWithdrawal")
	proto.RegisterType((*MsgAuthorizeWithdrawalResponse)(nil), "godchain.godbridge.v1.MsgAuthorizeWithdrawalResponse")
	proto.RegisterType((*MsgResolvePayment)(nil), "godchain.godbridge.v1.MsgResolvePayment")
	proto.RegisterType((*MsgResolvePaymentResponse)(nil), "godchain.godbridge.v1.MsgResolvePaymentResponse")
	proto.RegisterType((*MsgCancelWithdrawal)(nil), "godchain.godbridge.v1.MsgCancelWithdrawal")
	proto.RegisterType((*MsgCancelWithdrawalResponse)(nil), "godchain.godbridge.v1.MsgCancelWithdrawalResponse")
	proto.RegisterType((*MsgPauseBridge)(nil), "godchain.godbridge.v1.MsgPauseBridge")
	proto.RegisterType((*MsgPauseBridgeResponse)(nil), "godchain.godbridge.v1.MsgPauseBridgeResponse")
}

func init() { proto.RegisterFile("godchain/godbridge/v1/tx.proto", fileDescriptor_6f9f64153a06c9c8) }

var fileDescriptor_6f9f64153a06c9c8 = []byte{
	// 782 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0x4d, 0x4f, 0xdb, 0x4a,
	0x14, 0xc5, 0x24, 0xe1, 0x25, 0x17, 0xc2, 0x87, 0x79, 0x8f, 0xe7, 0x67, 0xc0, 0x8a, 0x82, 0xd0,
	0x4b, 0xa9, 0x88, 0x0b, 0xa8, 0x9b, 0xee, 0xf8, 0x12, 0xa0, 0x2a, 0x80, 0x4c, 0xa5, 0x4a, 0xdd,
	0x44, 0x8e, 0x3d, 0xb5, 0x47, 0x38, 0x9e, 0xd4, 0x33, 0x0e, 0xb4, 0x95, 0xaa, 0xaa, 0x7f, 0xa0,
	0xfd, 0x1d, 0x5d, 0xd1, 0xfe, 0x8a, 0x2e, 0x59, 0x76, 0x59, 0xc1, 0x82, 0x65, 0xd5, 0x65, 0x77,
	0x95, 0x27, 0x8e, 0xe3, 0x7c, 0x2a, 0x48, 0x15, 0x5d, 0xde, 0x3b, 0x67, 0xe6, 0x9e, 0x73, 0xee,
	0xcc, 0xd5, 0x80, 0x62, 0x11, 0xd3, 0xb0, 0x75, 0xec, 0xaa, 0x16, 0x31, 0x2b, 0x1e, 0x36, 0x2d,
	0xa4, 0xd6, 0xd7, 0x54, 0x76, 0x5e, 0xac, 0x79, 0x84, 0x11, 0xf1, 0x9f, 0xe6, 0x7a, 0x31, 0x5a,
	0x2f, 0xd6, 0xd7, 0xe4, 0x7f, 0x0d, 0x42, 0xab, 0x84, 0xaa, 0x55, 0x6a, 0x05, 0xf0, 0x2a, 0xb5,
	0x1a, 0xf8, 0xfc, 0x7b, 0x01, 0x26, 0x4f, 0x88, 0xef, 0x19, 0x68, 0xb7, 0x8e, 0x4d, 0xe4, 0x1a,
	0x48, 0x9c, 0x83, 0x31, 0x1b, 0x61, 0xcb, 0x66, 0x92, 0x90, 0x13, 0x0a, 0x49, 0x2d, 0x8c, 0xc4,
	0x45, 0x80, 0x8a, 0x43, 0x8c, 0xd3, 0xb2, 0xad, 0x53, 0x5b, 0x1a, 0xcd, 0x09, 0x85, 0x09, 0x2d,
	0xc3, 0x33, 0xfb, 0x3a, 0xb5, 0xc5, 0x7b, 0x30, 0xcd, 0x3c, 0xdd, 0xa5, 0xba, 0xc1, 0x30, 0x71,
	0x1b, 0xa0, 0x04, 0x07, 0x4d, 0xc5, 0xf2, 0x1c, 0x3a, 0x0f, 0x19, 0x87, 0x58, 0x65, 0xec, 0x9a,
	0xe8, 0x5c, 0x4a, 0xe6, 0x84, 0x42, 0x56, 0x4b, 0x3b, 0xc4, 0x3a, 0x08, 0xe2, 0xfc, 0x4f, 0x01,
	0xa6, 0x4b, 0xd4, 0xda, 0x34, 0x0c, 0x54, 0x63, 0x3b, 0xa8, 0x46, 0x28, 0x66, 0x01, 0x27, 0x8a,
	0x5c, 0x13, 0x79, 0x9c, 0x53, 0x46, 0x0b, 0xa3, 0xa0, 0xa8, 0xd9, 0x80, 0x94, 0x29, 0x7a, 0xe1,
	0x07, 0xfc, 0x39, 0xb3, 0xa4, 0x36, 0x15, 0xe6, 0x4f, 0xc2, 0xb4, 0xb8, 0x00, 0x19, 0x0f, 0x19,
	0xb8, 0x86, 0x91, 0xcb, 0x38, 0xb1, 0x8c, 0xd6, 0x4a, 0x04, 0x05, 0xf4, 0x2a, 0xf1, 0x5d, 0xc6,
	0xf9, 0x64, 0xb4, 0x30, 0x12, 0x37, 0x21, 0x8d, 0x42, 0x63, 0xa4, 0x54, 0x4e, 0x28, 0x8c, 0xaf,
	0x2f, 0x17, 0x7b, 0x5a, 0x5c, 0x6c, 0x77, 0x51, 0x8b, 0xb6, 0x05, 0x85, 0xf5, 0x5a, 0xcd, 0x23,
	0x75, 0xdd, 0xa1, 0xd2, 0x58, 0x2e, 0x11, 0xd8, 0x16, 0x25, 0x1e, 0x8d, 0xbf, 0xbb, 0xb9, 0x58,
	0x09, 0xe5, 0xe4, 0x65, 0x90, 0x3a, 0xa5, 0x6b, 0x88, 0xd6, 0x88, 0x4b, 0x51, 0xfe, 0x0d, 0xfc,
	0x5d, 0xa2, 0x96, 0x16, 0xc8, 0xa1, 0xec, 0x29, 0x66, 0xb6, 0xe9, 0xe9, 0x67, 0xba, 0x33, 0xc8,
	0x1a, 0xca, 0x29, 0x95, 0x5b, 0xb2, 0x1b, 0x4d, 0x9b, 0x6a, 0xe4, 0xb5, 0x1e, 0xe2, 0x13, 0x71,
	0xf1, 0xed, 0xdc, 0x18, 0x2c, 0xf4, 0xaa, 0xdf, 0xe4, 0x27, 0xaa, 0x30, 0x7b, 0x16, 0x65, 0x5b,
	0xdd, 0x68, 0xdc, 0x21, 0xb1, 0xb5, 0x14, 0x35, 0x64, 0x09, 0xb2, 0xb1, 0x0d, 0xd8, 0x0c, 0xd9,
	0x4d, 0xb4, 0x92, 0x07, 0x66, 0xfe, 0x93, 0x00, 0x73, 0x81, 0x25, 0x3e, 0xb3, 0x89, 0x87, 0x5f,
	0xa1, 0x21, 0x84, 0xf7, 0x21, 0x32, 0x3a, 0x3c, 0x91, 0x44, 0x37, 0x91, 0xf6, 0x2e, 0x26, 0x07,
	0x76, 0x31, 0x07, 0x4a, 0x6f, 0xca, 0x51, 0x2f, 0xbf, 0x0b, 0x30, 0xc3, 0xcd, 0xa4, 0xc4, 0xa9,
	0xa3, 0x63, 0xfd, 0x65, 0x35, 0x6c, 0xc3, 0x1d, 0x0a, 0x8a, 0xdf, 0xec, 0xe4, 0x6f, 0xb8, 0xd9,
	0xa9, 0x81, 0x9e, 0xcc, 0xc3, 0x7f, 0x5d, 0x82, 0x23, 0x3b, 0x7e, 0x08, 0x30, 0x5b, 0xa2, 0xd6,
	0xb6, 0xee, 0x1a, 0xc8, 0xf9, 0x63, 0x1d, 0xbe, 0x5b, 0x43, 0x16, 0x61, 0xbe, 0x87, 0xe4, 0xc8,
	0x92, 0x8f, 0x02, 0x4c, 0x96, 0xa8, 0x75, 0xac, 0xfb, 0x14, 0x6d, 0xf1, 0xc2, 0x7d, 0xdd, 0x58,
	0x82, 0xac, 0x41, 0x5c, 0xe6, 0x11, 0xa7, 0xec, 0x92, 0x96, 0x0f, 0x13, 0x61, 0xf2, 0x90, 0x84,
	0x43, 0x1d, 0xbb, 0x4c, 0x3f, 0x45, 0x5c, 0x7a, 0x5a, 0x0b, 0x23, 0x51, 0x82, 0xbf, 0x88, 0xcf,
	0x9e, 0x3b, 0xe4, 0x8c, 0x6b, 0x4e, 0x6b, 0xcd, 0xf0, 0x36, 0x5a, 0x24, 0xfe, 0x46, 0x63, 0x5c,
	0x9b, 0x32, 0xd6, 0x3f, 0xa7, 0x20, 0x51, 0xa2, 0x96, 0x88, 0x21, 0xdb, 0x3e, 0xd0, 0xff, 0xef,
	0x63, 0x6d, 0xe7, 0xf8, 0x93, 0xd5, 0x21, 0x81, 0xd1, 0x1c, 0xf2, 0x61, 0xa6, 0x7b, 0x48, 0xde,
	0xef, 0x7f, 0x4a, 0x17, 0x58, 0xde, 0xb8, 0x05, 0x38, 0x2a, 0xfb, 0x1a, 0x66, 0x7b, 0x0d, 0xa9,
	0xd5, 0x01, 0xf4, 0xbb, 0xe1, 0xf2, 0xc3, 0x5b, 0xc1, 0xa3, 0xe2, 0x0e, 0x4c, 0x76, 0xcc, 0x92,
	0xc2, 0x20, 0x0d, 0x71, 0xa4, 0xfc, 0x60, 0x58, 0x64, 0x54, 0xcd, 0x83, 0xe9, 0xae, 0xa7, 0xba,
	0xd2, 0xff, 0x94, 0x4e, 0xac, 0xbc, 0x3e, 0x3c, 0x36, 0xaa, 0x69, 0xc0, 0x78, 0xfc, 0x2d, 0x2c,
	0xf7, 0x3f, 0x22, 0x06, 0x93, 0x57, 0x87, 0x82, 0x35, 0x8b, 0xc8, 0xa9, 0xb7, 0x37, 0x17, 0x2b,
	0xc2, 0xd6, 0xfe, 0x97, 0x2b, 0x45, 0xb8, 0xbc, 0x52, 0x84, 0x6f, 0x57, 0x8a, 0xf0, 0xe1, 0x5a,
	0x19, 0xb9, 0xbc, 0x56, 0x46, 0xbe, 0x5e, 0x2b, 0x23, 0xcf, 0x8a, 0x16, 0x66, 0xb6, 0x5f, 0x29,
	0x1a, 0xa4, 0xaa, 0xee, 0x3e, 0x79, 0x7c, 0x70, 0xb8, 0xb7, 0x73, 0x54, 0x52, 0xf7, 0x8e, 0x76,
	0x56, 0xb7, 0xf9, 0x9f, 0xec, 0x3c, 0xf6, 0x2b, 0xab, 0x52, 0xab, 0x32, 0xc6, 0x3f, 0x59, 0x1b,
	0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x2a, 0x55, 0x84, 0x52, 0xb6, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	AcceptDeposit(ctx context.Context, in *MsgAcceptDeposit, opts ...grpc.CallOption) (*MsgAcceptDepositResponse, error)
	RequestWithdrawal(ctx context.Context, in *MsgRequestWithdrawal, opts ...grpc.CallOption) (*MsgRequestWithdrawalResponse, error)
	AuthorizeWithdrawal(ctx context.Context, in *MsgAuthorizeWithdrawal, opts ...grpc.CallOption) (*MsgAuthorizeWithdrawalResponse, error)
	ResolvePayment(ctx context.Context, in *MsgResolvePayment, opts ...grpc.CallOption) (*MsgResolvePaymentResponse, error)
	CancelWithdrawal(ctx context.Context, in *MsgCancelWithdrawal, opts ...grpc.CallOption) (*MsgCancelWithdrawalResponse, error)
	PauseBridge(ctx context.Context, in *MsgPauseBridge, opts ...grpc.CallOption) (*MsgPauseBridgeResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) AcceptDeposit(ctx context.Context, in *MsgAcceptDeposit, opts ...grpc.CallOption) (*MsgAcceptDepositResponse, error) {
	out := new(MsgAcceptDepositResponse)
	err := c.cc.Invoke(ctx, "/godchain.godbridge.v1.Msg/AcceptDeposit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RequestWithdrawal(ctx context.Context, in *MsgRequestWithdrawal, opts ...grpc.CallOption) (*MsgRequestWithdrawalResponse, error) {
	out := new(MsgRequestWithdrawalResponse)
	err := c.cc.Invoke(ctx, "/godchain.godbridge.v1.Msg/RequestWithdrawal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) AuthorizeWithdrawal(ctx context.Context, in *MsgAuthorizeWithdrawal, opts ...grpc.CallOption) (*MsgAuthorizeWithdrawalResponse, error) {
	out := new(MsgAuthorizeWithdrawalResponse)
	err := c.cc.Invoke(ctx, "/godchain.godbridge.v1.Msg/AuthorizeWithdrawal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ResolvePayment(ctx context.Context, in *MsgResolvePayment, opts ...grpc.CallOption) (*MsgResolvePaymentResponse, error) {
	out := new(MsgResolvePaymentResponse)
	err := c.cc.Invoke(ctx, "/godchain.godbridge.v1.Msg/ResolvePayment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CancelWithdrawal(ctx context.Context, in *MsgCancelWithdrawal, opts ...grpc.CallOption) (*MsgCancelWithdrawalResponse, error) {
	out := new(MsgCancelWithdrawalResponse)
	err := c.cc.Invoke(ctx, "/godchain.godbridge.v1.Msg/CancelWithdrawal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) PauseBridge(ctx context.Context, in *MsgPauseBridge, opts ...grpc.CallOption) (*MsgPauseBridgeResponse, error) {
	out := new(MsgPauseBridgeResponse)
	err := c.cc.Invoke(ctx, "/godchain.godbridge.v1.Msg/PauseBridge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	AcceptDeposit(context.Context, *MsgAcceptDeposit) (*MsgAcceptDepositResponse, error)
	RequestWithdrawal(context.Context, *MsgRequestWithdrawal) (*MsgRequestWithdrawalResponse, error)
	AuthorizeWithdrawal(context.Context, *MsgAuthorizeWithdrawal) (*MsgAuthorizeWithdrawalResponse, error)
	ResolvePayment(context.Context, *MsgResolvePayment) (*MsgResolvePaymentResponse, error)
	CancelWithdrawal(context.Context, *MsgCancelWithdrawal) (*MsgCancelWithdrawalResponse, error)
	PauseBridge(context.Context, *MsgPauseBridge) (*MsgPauseBridgeResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) AcceptDeposit(ctx context.Context, req *MsgAcceptDeposit) (*MsgAcceptDepositResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcceptDeposit not implemented")
}
func (*UnimplementedMsgServer) RequestWithdrawal(ctx context.Context, req *MsgRequestWithdrawal) (*MsgRequestWithdrawalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestWithdrawal not implemented")
}
func (*UnimplementedMsgServer) AuthorizeWithdrawal(ctx context.Context, req *MsgAuthorizeWithdrawal) (*MsgAuthorizeWithdrawalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthorizeWithdrawal not implemented")
}
func (*UnimplementedMsgServer) ResolvePayment(ctx context.Context, req *MsgResolvePayment) (*MsgResolvePaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolvePayment not implemented")
}
func (*UnimplementedMsgServer) CancelWithdrawal(ctx context.Context, req *MsgCancelWithdrawal) (*MsgCancelWithdrawalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelWithdrawal not implemented")
}
func (*UnimplementedMsgServer) PauseBridge(ctx context.Context, req *MsgPauseBridge) (*MsgPauseBridgeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PauseBridge not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_AcceptDeposit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAcceptDeposit)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AcceptDeposit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/godchain.godbridge.v1.Msg/AcceptDeposit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AcceptDeposit(ctx, req.(*MsgAcceptDeposit))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RequestWithdrawal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRequestWithdrawal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RequestWithdrawal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/godchain.godbridge.v1.Msg/RequestWithdrawal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RequestWithdrawal(ctx, req.(*MsgRequestWithdrawal))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_AuthorizeWithdrawal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAuthorizeWithdrawal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AuthorizeWithdrawal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/godchain.godbridge.v1.Msg/AuthorizeWithdrawal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AuthorizeWithdrawal(ctx, req.(*MsgAuthorizeWithdrawal))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ResolvePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgResolvePayment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ResolvePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/godchain.godbridge.v1.Msg/ResolvePayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ResolvePayment(ctx, req.(*MsgResolvePayment))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CancelWithdrawal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCancelWithdrawal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CancelWithdrawal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/godchain.godbridge.v1.Msg/CancelWithdrawal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CancelWithdrawal(ctx, req.(*MsgCancelWithdrawal))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_PauseBridge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgPauseBridge)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).PauseBridge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/godchain.godbridge.v1.Msg/PauseBridge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).PauseBridge(ctx, req.(*MsgPauseBridge))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "godchain.godbridge.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AcceptDeposit",
			Handler:    _Msg_AcceptDeposit_Handler,
		},
		{
			MethodName: "RequestWithdrawal",
			Handler:    _Msg_RequestWithdrawal_Handler,
		},
		{
			MethodName: "AuthorizeWithdrawal",
			Handler:    _Msg_AuthorizeWithdrawal_Handler,
		},
		{
			MethodName: "ResolvePayment",
			Handler:    _Msg_ResolvePayment_Handler,
		},
		{
			MethodName: "CancelWithdrawal",
			Handler:    _Msg_CancelWithdrawal_Handler,
		},
		{
			MethodName: "PauseBridge",
			Handler:    _Msg_PauseBridge_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "godchain/godbridge/v1/tx.proto",
}

func (m *SourceEvidence) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SourceEvidence) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SourceEvidence) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LogIndex != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.LogIndex))
		i--
		dAtA[i] = 0x20
	}
	if len(m.TransactionHash) > 0 {
		i -= len(m.TransactionHash)
		copy(dAtA[i:], m.TransactionHash)
		i = encodeVarintTx(dAtA, i, uint64(len(m.TransactionHash)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.BlockHash) > 0 {
		i -= len(m.BlockHash)
		copy(dAtA[i:], m.BlockHash)
		i = encodeVarintTx(dAtA, i, uint64(len(m.BlockHash)))
		i--
		dAtA[i] = 0x12
	}
	if m.Height != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgAcceptDeposit) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAcceptDeposit) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAcceptDeposit) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Approvals) > 0 {
		for iNdEx := len(m.Approvals) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Approvals[iNdEx])
			copy(dAtA[i:], m.Approvals[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.Approvals[iNdEx])))
			i--
			dAtA[i] = 0x32
		}
	}
	if m.Evidence != nil {
		{
			size, err := m.Evidence.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Amount) > 0 {
		i -= len(m.Amount)
		copy(dAtA[i:], m.Amount)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Amount)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Recipient) > 0 {
		i -= len(m.Recipient)
		copy(dAtA[i:], m.Recipient)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Recipient)))
		i--
		dAtA[i] = 0x1a
	}
	if m.DepositSequence != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.DepositSequence))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgAcceptDepositResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAcceptDepositResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAcceptDepositResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgRequestWithdrawal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRequestWithdrawal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRequestWithdrawal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Amount) > 0 {
		i -= len(m.Amount)
		copy(dAtA[i:], m.Amount)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Amount)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.SourceRecipient) > 0 {
		i -= len(m.SourceRecipient)
		copy(dAtA[i:], m.SourceRecipient)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SourceRecipient)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRequestWithdrawalResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRequestWithdrawalResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRequestWithdrawalResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.WithdrawalId) > 0 {
		i -= len(m.WithdrawalId)
		copy(dAtA[i:], m.WithdrawalId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.WithdrawalId)))
		i--
		dAtA[i] = 0x12
	}
	if m.WithdrawalSequence != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.WithdrawalSequence))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgAuthorizeWithdrawal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAuthorizeWithdrawal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAuthorizeWithdrawal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Approvals) > 0 {
		for iNdEx := len(m.Approvals) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Approvals[iNdEx])
			copy(dAtA[i:], m.Approvals[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.Approvals[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.WithdrawalId) > 0 {
		i -= len(m.WithdrawalId)
		copy(dAtA[i:], m.WithdrawalId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.WithdrawalId)))
		i--
		dAtA[i] = 0x1a
	}
	if m.WithdrawalSequence != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.WithdrawalSequence))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgAuthorizeWithdrawalResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAuthorizeWithdrawalResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAuthorizeWithdrawalResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgResolvePayment) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgResolvePayment) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgResolvePayment) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Approvals) > 0 {
		for iNdEx := len(m.Approvals) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Approvals[iNdEx])
			copy(dAtA[i:], m.Approvals[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.Approvals[iNdEx])))
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.Evidence != nil {
		{
			size, err := m.Evidence.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if len(m.WithdrawalId) > 0 {
		i -= len(m.WithdrawalId)
		copy(dAtA[i:], m.WithdrawalId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.WithdrawalId)))
		i--
		dAtA[i] = 0x1a
	}
	if m.WithdrawalSequence != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.WithdrawalSequence))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgResolvePaymentResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgResolvePaymentResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgResolvePaymentResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgCancelWithdrawal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCancelWithdrawal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCancelWithdrawal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Approvals) > 0 {
		for iNdEx := len(m.Approvals) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Approvals[iNdEx])
			copy(dAtA[i:], m.Approvals[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.Approvals[iNdEx])))
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.Evidence != nil {
		{
			size, err := m.Evidence.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if len(m.WithdrawalId) > 0 {
		i -= len(m.WithdrawalId)
		copy(dAtA[i:], m.WithdrawalId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.WithdrawalId)))
		i--
		dAtA[i] = 0x1a
	}
	if m.WithdrawalSequence != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.WithdrawalSequence))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCancelWithdrawalResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCancelWithdrawalResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCancelWithdrawalResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgPauseBridge) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgPauseBridge) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgPauseBridge) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Approvals) > 0 {
		for iNdEx := len(m.Approvals) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Approvals[iNdEx])
			copy(dAtA[i:], m.Approvals[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.Approvals[iNdEx])))
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.Outflow {
		i--
		if m.Outflow {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if m.Intake {
		i--
		if m.Intake {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.ControlNonce != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ControlNonce))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgPauseBridgeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgPauseBridgeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgPauseBridgeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SourceEvidence) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Height != 0 {
		n += 1 + sovTx(uint64(m.Height))
	}
	l = len(m.BlockHash)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.TransactionHash)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.LogIndex != 0 {
		n += 1 + sovTx(uint64(m.LogIndex))
	}
	return n
}

func (m *MsgAcceptDeposit) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.DepositSequence != 0 {
		n += 1 + sovTx(uint64(m.DepositSequence))
	}
	l = len(m.Recipient)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Amount)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Evidence != nil {
		l = m.Evidence.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Approvals) > 0 {
		for _, b := range m.Approvals {
			l = len(b)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgAcceptDepositResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgRequestWithdrawal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.SourceRecipient)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Amount)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRequestWithdrawalResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.WithdrawalSequence != 0 {
		n += 1 + sovTx(uint64(m.WithdrawalSequence))
	}
	l = len(m.WithdrawalId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgAuthorizeWithdrawal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.WithdrawalSequence != 0 {
		n += 1 + sovTx(uint64(m.WithdrawalSequence))
	}
	l = len(m.WithdrawalId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Approvals) > 0 {
		for _, b := range m.Approvals {
			l = len(b)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgAuthorizeWithdrawalResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgResolvePayment) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.WithdrawalSequence != 0 {
		n += 1 + sovTx(uint64(m.WithdrawalSequence))
	}
	l = len(m.WithdrawalId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Evidence != nil {
		l = m.Evidence.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Approvals) > 0 {
		for _, b := range m.Approvals {
			l = len(b)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgResolvePaymentResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgCancelWithdrawal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.WithdrawalSequence != 0 {
		n += 1 + sovTx(uint64(m.WithdrawalSequence))
	}
	l = len(m.WithdrawalId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Evidence != nil {
		l = m.Evidence.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Approvals) > 0 {
		for _, b := range m.Approvals {
			l = len(b)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgCancelWithdrawalResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgPauseBridge) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.ControlNonce != 0 {
		n += 1 + sovTx(uint64(m.ControlNonce))
	}
	if m.Intake {
		n += 2
	}
	if m.Outflow {
		n += 2
	}
	if len(m.Approvals) > 0 {
		for _, b := range m.Approvals {
			l = len(b)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgPauseBridgeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SourceEvidence) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SourceEvidence: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SourceEvidence: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BlockHash = append(m.BlockHash[:0], dAtA[iNdEx:postIndex]...)
			if m.BlockHash == nil {
				m.BlockHash = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TransactionHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TransactionHash = append(m.TransactionHash[:0], dAtA[iNdEx:postIndex]...)
			if m.TransactionHash == nil {
				m.TransactionHash = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LogIndex", wireType)
			}
			m.LogIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LogIndex |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAcceptDeposit) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAcceptDeposit: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAcceptDeposit: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepositSequence", wireType)
			}
			m.DepositSequence = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DepositSequence |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Recipient", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Recipient = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Evidence", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Evidence == nil {
				m.Evidence = &SourceEvidence{}
			}
			if err := m.Evidence.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Approvals", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Approvals = append(m.Approvals, make([]byte, postIndex-iNdEx))
			copy(m.Approvals[len(m.Approvals)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAcceptDepositResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAcceptDepositResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAcceptDepositResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRequestWithdrawal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRequestWithdrawal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRequestWithdrawal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceRecipient", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourceRecipient = append(m.SourceRecipient[:0], dAtA[iNdEx:postIndex]...)
			if m.SourceRecipient == nil {
				m.SourceRecipient = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRequestWithdrawalResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRequestWithdrawalResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRequestWithdrawalResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithdrawalSequence", wireType)
			}
			m.WithdrawalSequence = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WithdrawalSequence |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithdrawalId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WithdrawalId = append(m.WithdrawalId[:0], dAtA[iNdEx:postIndex]...)
			if m.WithdrawalId == nil {
				m.WithdrawalId = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAuthorizeWithdrawal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAuthorizeWithdrawal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAuthorizeWithdrawal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithdrawalSequence", wireType)
			}
			m.WithdrawalSequence = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WithdrawalSequence |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithdrawalId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WithdrawalId = append(m.WithdrawalId[:0], dAtA[iNdEx:postIndex]...)
			if m.WithdrawalId == nil {
				m.WithdrawalId = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Approvals", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Approvals = append(m.Approvals, make([]byte, postIndex-iNdEx))
			copy(m.Approvals[len(m.Approvals)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAuthorizeWithdrawalResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAuthorizeWithdrawalResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAuthorizeWithdrawalResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgResolvePayment) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgResolvePayment: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgResolvePayment: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithdrawalSequence", wireType)
			}
			m.WithdrawalSequence = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WithdrawalSequence |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithdrawalId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WithdrawalId = append(m.WithdrawalId[:0], dAtA[iNdEx:postIndex]...)
			if m.WithdrawalId == nil {
				m.WithdrawalId = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Evidence", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Evidence == nil {
				m.Evidence = &SourceEvidence{}
			}
			if err := m.Evidence.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Approvals", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Approvals = append(m.Approvals, make([]byte, postIndex-iNdEx))
			copy(m.Approvals[len(m.Approvals)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgResolvePaymentResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgResolvePaymentResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgResolvePaymentResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCancelWithdrawal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCancelWithdrawal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCancelWithdrawal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithdrawalSequence", wireType)
			}
			m.WithdrawalSequence = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WithdrawalSequence |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithdrawalId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WithdrawalId = append(m.WithdrawalId[:0], dAtA[iNdEx:postIndex]...)
			if m.WithdrawalId == nil {
				m.WithdrawalId = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Evidence", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Evidence == nil {
				m.Evidence = &SourceEvidence{}
			}
			if err := m.Evidence.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Approvals", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Approvals = append(m.Approvals, make([]byte, postIndex-iNdEx))
			copy(m.Approvals[len(m.Approvals)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCancelWithdrawalResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCancelWithdrawalResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCancelWithdrawalResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgPauseBridge) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgPauseBridge: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgPauseBridge: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ControlNonce", wireType)
			}
			m.ControlNonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ControlNonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Intake", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Intake = bool(v != 0)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Outflow", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Outflow = bool(v != 0)
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Approvals", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Approvals = append(m.Approvals, make([]byte, postIndex-iNdEx))
			copy(m.Approvals[len(m.Approvals)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgPauseBridgeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgPauseBridgeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgPauseBridgeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
