// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: godchain/godrewards/v1/tx.proto

package msg

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgClaimG struct {
	Sender string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
}

func (m *MsgClaimG) Reset()         { *m = MsgClaimG{} }
func (m *MsgClaimG) String() string { return proto.CompactTextString(m) }
func (*MsgClaimG) ProtoMessage()    {}
func (*MsgClaimG) Descriptor() ([]byte, []int) {
	return fileDescriptor_6625fc48b20bf797, []int{0}
}
func (m *MsgClaimG) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgClaimG) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgClaimG.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgClaimG) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClaimG.Merge(m, src)
}
func (m *MsgClaimG) XXX_Size() int {
	return m.Size()
}
func (m *MsgClaimG) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClaimG.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClaimG proto.InternalMessageInfo

func (m *MsgClaimG) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

type MsgClaimGResponse struct {
}

func (m *MsgClaimGResponse) Reset()         { *m = MsgClaimGResponse{} }
func (m *MsgClaimGResponse) String() string { return proto.CompactTextString(m) }
func (*MsgClaimGResponse) ProtoMessage()    {}
func (*MsgClaimGResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6625fc48b20bf797, []int{1}
}
func (m *MsgClaimGResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgClaimGResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgClaimGResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgClaimGResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClaimGResponse.Merge(m, src)
}
func (m *MsgClaimGResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgClaimGResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClaimGResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClaimGResponse proto.InternalMessageInfo

type MsgTransferG struct {
	Sender    string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Recipient string `protobuf:"bytes,2,opt,name=recipient,proto3" json:"recipient,omitempty"`
	// Canonical positive decimal integer in smallest units, not floating point.
	Amount string `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *MsgTransferG) Reset()         { *m = MsgTransferG{} }
func (m *MsgTransferG) String() string { return proto.CompactTextString(m) }
func (*MsgTransferG) ProtoMessage()    {}
func (*MsgTransferG) Descriptor() ([]byte, []int) {
	return fileDescriptor_6625fc48b20bf797, []int{2}
}
func (m *MsgTransferG) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgTransferG) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgTransferG.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgTransferG) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgTransferG.Merge(m, src)
}
func (m *MsgTransferG) XXX_Size() int {
	return m.Size()
}
func (m *MsgTransferG) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgTransferG.DiscardUnknown(m)
}

var xxx_messageInfo_MsgTransferG proto.InternalMessageInfo

func (m *MsgTransferG) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgTransferG) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

func (m *MsgTransferG) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

type MsgTransferGResponse struct {
}

func (m *MsgTransferGResponse) Reset()         { *m = MsgTransferGResponse{} }
func (m *MsgTransferGResponse) String() string { return proto.CompactTextString(m) }
func (*MsgTransferGResponse) ProtoMessage()    {}
func (*MsgTransferGResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6625fc48b20bf797, []int{3}
}
func (m *MsgTransferGResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgTransferGResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgTransferGResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgTransferGResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgTransferGResponse.Merge(m, src)
}
func (m *MsgTransferGResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgTransferGResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgTransferGResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgTransferGResponse proto.InternalMessageInfo

type MsgLockG struct {
	Sender string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	LockId string `protobuf:"bytes,2,opt,name=lock_id,json=lockId,proto3" json:"lock_id,omitempty"`
	Amount string `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *MsgLockG) Reset()         { *m = MsgLockG{} }
func (m *MsgLockG) String() string { return proto.CompactTextString(m) }
func (*MsgLockG) ProtoMessage()    {}
func (*MsgLockG) Descriptor() ([]byte, []int) {
	return fileDescriptor_6625fc48b20bf797, []int{4}
}
func (m *MsgLockG) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgLockG) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgLockG.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgLockG) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgLockG.Merge(m, src)
}
func (m *MsgLockG) XXX_Size() int {
	return m.Size()
}
func (m *MsgLockG) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgLockG.DiscardUnknown(m)
}

var xxx_messageInfo_MsgLockG proto.InternalMessageInfo

func (m *MsgLockG) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgLockG) GetLockId() string {
	if m != nil {
		return m.LockId
	}
	return ""
}

func (m *MsgLockG) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

type MsgLockGResponse struct {
}

func (m *MsgLockGResponse) Reset()         { *m = MsgLockGResponse{} }
func (m *MsgLockGResponse) String() string { return proto.CompactTextString(m) }
func (*MsgLockGResponse) ProtoMessage()    {}
func (*MsgLockGResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6625fc48b20bf797, []int{5}
}
func (m *MsgLockGResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgLockGResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgLockGResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgLockGResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgLockGResponse.Merge(m, src)
}
func (m *MsgLockGResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgLockGResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgLockGResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgLockGResponse proto.InternalMessageInfo

type MsgUnlockG struct {
	Sender string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	LockId string `protobuf:"bytes,2,opt,name=lock_id,json=lockId,proto3" json:"lock_id,omitempty"`
}

func (m *MsgUnlockG) Reset()         { *m = MsgUnlockG{} }
func (m *MsgUnlockG) String() string { return proto.CompactTextString(m) }
func (*MsgUnlockG) ProtoMessage()    {}
func (*MsgUnlockG) Descriptor() ([]byte, []int) {
	return fileDescriptor_6625fc48b20bf797, []int{6}
}
func (m *MsgUnlockG) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUnlockG) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUnlockG.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUnlockG) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUnlockG.Merge(m, src)
}
func (m *MsgUnlockG) XXX_Size() int {
	return m.Size()
}
func (m *MsgUnlockG) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUnlockG.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUnlockG proto.InternalMessageInfo

func (m *MsgUnlockG) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgUnlockG) GetLockId() string {
	if m != nil {
		return m.LockId
	}
	return ""
}

type MsgUnlockGResponse struct {
}

func (m *MsgUnlockGResponse) Reset()         { *m = MsgUnlockGResponse{} }
func (m *MsgUnlockGResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUnlockGResponse) ProtoMessage()    {}
func (*MsgUnlockGResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6625fc48b20bf797, []int{7}
}
func (m *MsgUnlockGResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUnlockGResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUnlockGResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUnlockGResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUnlockGResponse.Merge(m, src)
}
func (m *MsgUnlockGResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUnlockGResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUnlockGResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUnlockGResponse proto.InternalMessageInfo

type MsgRedeemG struct {
	Sender      string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Beneficiary string `protobuf:"bytes,2,opt,name=beneficiary,proto3" json:"beneficiary,omitempty"`
	Amount      string `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	MinGodOut   string `protobuf:"bytes,4,opt,name=min_god_out,json=minGodOut,proto3" json:"min_god_out,omitempty"`
	// Checked against consensus block time, not a participant's local clock.
	DeadlineUnixNanos int64 `protobuf:"varint,5,opt,name=deadline_unix_nanos,json=deadlineUnixNanos,proto3" json:"deadline_unix_nanos,omitempty"`
}

func (m *MsgRedeemG) Reset()         { *m = MsgRedeemG{} }
func (m *MsgRedeemG) String() string { return proto.CompactTextString(m) }
func (*MsgRedeemG) ProtoMessage()    {}
func (*MsgRedeemG) Descriptor() ([]byte, []int) {
	return fileDescriptor_6625fc48b20bf797, []int{8}
}
func (m *MsgRedeemG) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRedeemG) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRedeemG.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRedeemG) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRedeemG.Merge(m, src)
}
func (m *MsgRedeemG) XXX_Size() int {
	return m.Size()
}
func (m *MsgRedeemG) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRedeemG.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRedeemG proto.InternalMessageInfo

func (m *MsgRedeemG) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgRedeemG) GetBeneficiary() string {
	if m != nil {
		return m.Beneficiary
	}
	return ""
}

func (m *MsgRedeemG) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *MsgRedeemG) GetMinGodOut() string {
	if m != nil {
		return m.MinGodOut
	}
	return ""
}

func (m *MsgRedeemG) GetDeadlineUnixNanos() int64 {
	if m != nil {
		return m.DeadlineUnixNanos
	}
	return 0
}

type MsgRedeemGResponse struct {
	GodOut string `protobuf:"bytes,1,opt,name=god_out,json=godOut,proto3" json:"god_out,omitempty"`
}

func (m *MsgRedeemGResponse) Reset()         { *m = MsgRedeemGResponse{} }
func (m *MsgRedeemGResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRedeemGResponse) ProtoMessage()    {}
func (*MsgRedeemGResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6625fc48b20bf797, []int{9}
}
func (m *MsgRedeemGResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRedeemGResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRedeemGResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRedeemGResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRedeemGResponse.Merge(m, src)
}
func (m *MsgRedeemGResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRedeemGResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRedeemGResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRedeemGResponse proto.InternalMessageInfo

func (m *MsgRedeemGResponse) GetGodOut() string {
	if m != nil {
		return m.GodOut
	}
	return ""
}

type MsgDonateGod struct {
	Sender string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Amount string `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *MsgDonateGod) Reset()         { *m = MsgDonateGod{} }
func (m *MsgDonateGod) String() string { return proto.CompactTextString(m) }
func (*MsgDonateGod) ProtoMessage()    {}
func (*MsgDonateGod) Descriptor() ([]byte, []int) {
	return fileDescriptor_6625fc48b20bf797, []int{10}
}
func (m *MsgDonateGod) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDonateGod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDonateGod.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDonateGod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDonateGod.Merge(m, src)
}
func (m *MsgDonateGod) XXX_Size() int {
	return m.Size()
}
func (m *MsgDonateGod) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDonateGod.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDonateGod proto.InternalMessageInfo

func (m *MsgDonateGod) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgDonateGod) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

type MsgDonateGodResponse struct {
}

func (m *MsgDonateGodResponse) Reset()         { *m = MsgDonateGodResponse{} }
func (m *MsgDonateGodResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDonateGodResponse) ProtoMessage()    {}
func (*MsgDonateGodResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6625fc48b20bf797, []int{11}
}
func (m *MsgDonateGodResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDonateGodResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDonateGodResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDonateGodResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDonateGodResponse.Merge(m, src)
}
func (m *MsgDonateGodResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDonateGodResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDonateGodResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDonateGodResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgClaimG)(nil), "godchain.godrewards.v1.MsgClaimG")
	proto.RegisterType((*MsgClaimGResponse)(nil), "godchain.godrewards.v1.MsgClaimGResponse")
	proto.RegisterType((*MsgTransferG)(nil), "godchain.godrewards.v1.MsgTransferG")
	proto.RegisterType((*MsgTransferGResponse)(nil), "godchain.godrewards.v1.MsgTransferGResponse")
	proto.RegisterType((*MsgLockG)(nil), "godchain.godrewards.v1.MsgLockG")
	proto.RegisterType((*MsgLockGResponse)(nil), "godchain.godrewards.v1.MsgLockGResponse")
	proto.RegisterType((*MsgUnlockG)(nil), "godchain.godrewards.v1.MsgUnlockG")
	proto.RegisterType((*MsgUnlockGResponse)(nil), "godchain.godrewards.v1.MsgUnlockGResponse")
	proto.RegisterType((*MsgRedeemG)(nil), "godchain.godrewards.v1.MsgRedeemG")
	proto.RegisterType((*MsgRedeemGResponse)(nil), "godchain.godrewards.v1.MsgRedeemGResponse")
	proto.RegisterType((*MsgDonateGod)(nil), "godchain.godrewards.v1.MsgDonateGod")
	proto.RegisterType((*MsgDonateGodResponse)(nil), "godchain.godrewards.v1.MsgDonateGodResponse")
}

func init() { proto.RegisterFile("godchain/godrewards/v1/tx.proto", fileDescriptor_6625fc48b20bf797) }

var fileDescriptor_6625fc48b20bf797 = []byte{
	// 567 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0xcf, 0x6e, 0xd3, 0x4a,
	0x18, 0xc5, 0xe3, 0xa6, 0x49, 0x6f, 0xbe, 0xdc, 0x05, 0x75, 0xab, 0x34, 0xb2, 0x90, 0x09, 0x11,
	0x8b, 0x10, 0x51, 0x9b, 0xc2, 0x8e, 0x25, 0x0d, 0x8a, 0x42, 0x71, 0x23, 0x85, 0x16, 0x09, 0x36,
	0xc6, 0xf1, 0x4c, 0xa7, 0xa3, 0xc6, 0x33, 0x91, 0xc7, 0x29, 0x61, 0x87, 0x78, 0x02, 0x1e, 0xa5,
	0xac, 0x79, 0x01, 0x96, 0x5d, 0xb2, 0x44, 0xc9, 0xa2, 0xaf, 0x81, 0xe2, 0x3f, 0xe3, 0x04, 0xb0,
	0x53, 0xb1, 0x1c, 0xcf, 0xf9, 0xce, 0xcf, 0x67, 0x7c, 0x3c, 0x70, 0x8f, 0x70, 0xe4, 0x9e, 0x3b,
	0x94, 0x99, 0x84, 0x23, 0x1f, 0x7f, 0x70, 0x7c, 0x24, 0xcc, 0xcb, 0x03, 0x33, 0x98, 0x1a, 0x63,
	0x9f, 0x07, 0x5c, 0xad, 0x25, 0x02, 0x23, 0x15, 0x18, 0x97, 0x07, 0xda, 0x9e, 0xcb, 0x85, 0xc7,
	0x85, 0xe9, 0x09, 0xb2, 0xd0, 0x7b, 0x82, 0x44, 0x03, 0xcd, 0xc7, 0x50, 0xb1, 0x04, 0x39, 0x1c,
	0x39, 0xd4, 0xeb, 0xaa, 0x35, 0x28, 0x0b, 0xcc, 0x10, 0xf6, 0xeb, 0x4a, 0x43, 0x69, 0x55, 0x06,
	0xf1, 0xea, 0x59, 0xf5, 0xf3, 0xcd, 0x55, 0x3b, 0x5e, 0x34, 0x77, 0x60, 0x5b, 0x4e, 0x0c, 0xb0,
	0x18, 0x73, 0x26, 0x70, 0x93, 0xc2, 0xff, 0x96, 0x20, 0x27, 0xbe, 0xc3, 0xc4, 0x19, 0xf6, 0x33,
	0x9d, 0xd4, 0xbb, 0x50, 0xf1, 0xb1, 0x4b, 0xc7, 0x14, 0xb3, 0xa0, 0xbe, 0x11, 0x6e, 0xa5, 0x0f,
	0x16, 0x53, 0x8e, 0xc7, 0x27, 0x2c, 0xa8, 0x17, 0xa3, 0xa9, 0x68, 0xb5, 0xca, 0xaf, 0xc1, 0xee,
	0x32, 0x4a, 0xbe, 0xc2, 0x7b, 0xf8, 0xcf, 0x12, 0xe4, 0x15, 0x77, 0x2f, 0xb2, 0xf1, 0x7b, 0xb0,
	0x35, 0xe2, 0xee, 0x85, 0x4d, 0x51, 0x0c, 0x2f, 0x2f, 0x96, 0x3d, 0x74, 0x3b, 0xb2, 0x0a, 0x77,
	0x12, 0x82, 0xa4, 0xbe, 0x04, 0xb0, 0x04, 0x39, 0x65, 0xa3, 0x7f, 0xe2, 0xae, 0xfa, 0xef, 0x82,
	0x9a, 0x7a, 0x49, 0xc2, 0x37, 0x25, 0x44, 0x0c, 0x30, 0xc2, 0x38, 0xfb, 0x1b, 0xa9, 0x0d, 0xa8,
	0x0e, 0x31, 0xc3, 0x67, 0xd4, 0xa5, 0x8e, 0xff, 0x31, 0xc6, 0x2c, 0x3f, 0xca, 0xca, 0xa8, 0xea,
	0x50, 0xf5, 0x28, 0xb3, 0x09, 0x47, 0x36, 0x9f, 0x04, 0xf5, 0xcd, 0xe8, 0xab, 0x78, 0x94, 0x75,
	0x39, 0xea, 0x4f, 0x02, 0xd5, 0x80, 0x1d, 0x84, 0x1d, 0x34, 0xa2, 0x0c, 0xdb, 0x13, 0x46, 0xa7,
	0x36, 0x73, 0x18, 0x17, 0xf5, 0x52, 0x43, 0x69, 0x15, 0x07, 0xdb, 0xc9, 0xd6, 0x29, 0xa3, 0xd3,
	0xe3, 0xc5, 0xc6, 0x6a, 0xa6, 0xfd, 0x30, 0x53, 0xfc, 0xf2, 0x49, 0xa6, 0xc5, 0x79, 0x24, 0xb8,
	0x38, 0x05, 0x09, 0x59, 0xcd, 0xa3, 0xb0, 0x47, 0x1d, 0xce, 0x9c, 0x00, 0x77, 0x39, 0xca, 0x4c,
	0x9b, 0x66, 0xd9, 0x58, 0xd7, 0x14, 0x69, 0x96, 0xd0, 0x9f, 0x7c, 0xdd, 0x84, 0xa2, 0x25, 0x88,
	0xfa, 0x06, 0xca, 0x71, 0xf1, 0xef, 0x1b, 0x7f, 0xff, 0x6f, 0x0c, 0xd9, 0x74, 0xed, 0xe1, 0x5a,
	0x89, 0x4c, 0x67, 0x43, 0x25, 0xfd, 0x13, 0x1e, 0xe4, 0xcc, 0x49, 0x95, 0xf6, 0xe8, 0x36, 0x2a,
	0x09, 0x78, 0x0d, 0xa5, 0xa8, 0xe7, 0x8d, 0x9c, 0xb1, 0x50, 0xa1, 0xb5, 0xd6, 0x29, 0xa4, 0xe9,
	0x5b, 0xd8, 0x4a, 0x6a, 0xdc, 0xcc, 0x19, 0x8a, 0x35, 0x5a, 0x7b, 0xbd, 0x66, 0xd9, 0x3a, 0xa9,
	0x6f, 0x9e, 0x75, 0xac, 0xc9, 0xb5, 0xfe, 0xbd, 0x49, 0x36, 0x54, 0xd2, 0xb6, 0xe4, 0x9d, 0xb5,
	0x54, 0xe5, 0x9e, 0xf5, 0x1f, 0x65, 0xd1, 0x4a, 0x9f, 0x6e, 0xae, 0xda, 0xca, 0xf3, 0xde, 0xf7,
	0x99, 0xae, 0x5c, 0xcf, 0x74, 0xe5, 0xe7, 0x4c, 0x57, 0xbe, 0xcc, 0xf5, 0xc2, 0xf5, 0x5c, 0x2f,
	0xfc, 0x98, 0xeb, 0x85, 0x77, 0x26, 0xa1, 0xc1, 0xf9, 0x64, 0x68, 0xb8, 0xdc, 0x33, 0x5f, 0x9c,
	0x1c, 0xf5, 0x8e, 0xbb, 0x9d, 0xbe, 0x65, 0x76, 0xfb, 0x9d, 0xfd, 0xc3, 0xf0, 0xa6, 0x9e, 0x2e,
	0xdf, 0xd5, 0x9e, 0x20, 0xc3, 0x72, 0x78, 0xf3, 0x3e, 0xfd, 0x15, 0x00, 0x00, 0xff, 0xff, 0xd3,
	0xda, 0x97, 0xd6, 0xcd, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	ClaimG(ctx context.Context, in *MsgClaimG, opts ...grpc.CallOption) (*MsgClaimGResponse, error)
	TransferG(ctx context.Context, in *MsgTransferG, opts ...grpc.CallOption) (*MsgTransferGResponse, error)
	LockG(ctx context.Context, in *MsgLockG, opts ...grpc.CallOption) (*MsgLockGResponse, error)
	UnlockG(ctx context.Context, in *MsgUnlockG, opts ...grpc.CallOption) (*MsgUnlockGResponse, error)
	RedeemG(ctx context.Context, in *MsgRedeemG, opts ...grpc.CallOption) (*MsgRedeemGResponse, error)
	DonateGod(ctx context.Context, in *MsgDonateGod, opts ...grpc.CallOption) (*MsgDonateGodResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) ClaimG(ctx context.Context, in *MsgClaimG, opts ...grpc.CallOption) (*MsgClaimGResponse, error) {
	out := new(MsgClaimGResponse)
	err := c.cc.Invoke(ctx, "/godchain.godrewards.v1.Msg/ClaimG", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) TransferG(ctx context.Context, in *MsgTransferG, opts ...grpc.CallOption) (*MsgTransferGResponse, error) {
	out := new(MsgTransferGResponse)
	err := c.cc.Invoke(ctx, "/godchain.godrewards.v1.Msg/TransferG", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) LockG(ctx context.Context, in *MsgLockG, opts ...grpc.CallOption) (*MsgLockGResponse, error) {
	out := new(MsgLockGResponse)
	err := c.cc.Invoke(ctx, "/godchain.godrewards.v1.Msg/LockG", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UnlockG(ctx context.Context, in *MsgUnlockG, opts ...grpc.CallOption) (*MsgUnlockGResponse, error) {
	out := new(MsgUnlockGResponse)
	err := c.cc.Invoke(ctx, "/godchain.godrewards.v1.Msg/UnlockG", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RedeemG(ctx context.Context, in *MsgRedeemG, opts ...grpc.CallOption) (*MsgRedeemGResponse, error) {
	out := new(MsgRedeemGResponse)
	err := c.cc.Invoke(ctx, "/godchain.godrewards.v1.Msg/RedeemG", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DonateGod(ctx context.Context, in *MsgDonateGod, opts ...grpc.CallOption) (*MsgDonateGodResponse, error) {
	out := new(MsgDonateGodResponse)
	err := c.cc.Invoke(ctx, "/godchain.godrewards.v1.Msg/DonateGod", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	ClaimG(context.Context, *MsgClaimG) (*MsgClaimGResponse, error)
	TransferG(context.Context, *MsgTransferG) (*MsgTransferGResponse, error)
	LockG(context.Context, *MsgLockG) (*MsgLockGResponse, error)
	UnlockG(context.Context, *MsgUnlockG) (*MsgUnlockGResponse, error)
	RedeemG(context.Context, *MsgRedeemG) (*MsgRedeemGResponse, error)
	DonateGod(context.Context, *MsgDonateGod) (*MsgDonateGodResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) ClaimG(ctx context.Context, req *MsgClaimG) (*MsgClaimGResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClaimG not implemented")
}
func (*UnimplementedMsgServer) TransferG(ctx context.Context, req *MsgTransferG) (*MsgTransferGResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferG not implemented")
}
func (*UnimplementedMsgServer) LockG(ctx context.Context, req *MsgLockG) (*MsgLockGResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LockG not implemented")
}
func (*UnimplementedMsgServer) UnlockG(ctx context.Context, req *MsgUnlockG) (*MsgUnlockGResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnlockG not implemented")
}
func (*UnimplementedMsgServer) RedeemG(ctx context.Context, req *MsgRedeemG) (*MsgRedeemGResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RedeemG not implemented")
}
func (*UnimplementedMsgServer) DonateGod(ctx context.Context, req *MsgDonateGod) (*MsgDonateGodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DonateGod not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_ClaimG_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgClaimG)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ClaimG(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/godchain.godrewards.v1.Msg/ClaimG",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ClaimG(ctx, req.(*MsgClaimG))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_TransferG_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgTransferG)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).TransferG(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/godchain.godrewards.v1.Msg/TransferG",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).TransferG(ctx, req.(*MsgTransferG))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_LockG_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgLockG)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).LockG(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/godchain.godrewards.v1.Msg/LockG",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).LockG(ctx, req.(*MsgLockG))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UnlockG_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUnlockG)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UnlockG(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/godchain.godrewards.v1.Msg/UnlockG",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UnlockG(ctx, req.(*MsgUnlockG))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RedeemG_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRedeemG)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RedeemG(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/godchain.godrewards.v1.Msg/RedeemG",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RedeemG(ctx, req.(*MsgRedeemG))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DonateGod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDonateGod)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DonateGod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/godchain.godrewards.v1.Msg/DonateGod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DonateGod(ctx, req.(*MsgDonateGod))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "godchain.godrewards.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClaimG",
			Handler:    _Msg_ClaimG_Handler,
		},
		{
			MethodName: "TransferG",
			Handler:    _Msg_TransferG_Handler,
		},
		{
			MethodName: "LockG",
			Handler:    _Msg_LockG_Handler,
		},
		{
			MethodName: "UnlockG",
			Handler:    _Msg_UnlockG_Handler,
		},
		{
			MethodName: "RedeemG",
			Handler:    _Msg_RedeemG_Handler,
		},
		{
			MethodName: "DonateGod",
			Handler:    _Msg_DonateGod_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "godchain/godrewards/v1/tx.proto",
}

func (m *MsgClaimG) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgClaimG) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgClaimG) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgClaimGResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgClaimGResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgClaimGResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgTransferG) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgTransferG) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgTransferG) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Amount) > 0 {
		i -= len(m.Amount)
		copy(dAtA[i:], m.Amount)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Amount)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Recipient) > 0 {
		i -= len(m.Recipient)
		copy(dAtA[i:], m.Recipient)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Recipient)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgTransferGResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgTransferGResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgTransferGResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgLockG) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgLockG) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgLockG) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Amount) > 0 {
		i -= len(m.Amount)
		copy(dAtA[i:], m.Amount)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Amount)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.LockId) > 0 {
		i -= len(m.LockId)
		copy(dAtA[i:], m.LockId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.LockId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgLockGResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgLockGResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgLockGResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUnlockG) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUnlockG) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUnlockG) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.LockId) > 0 {
		i -= len(m.LockId)
		copy(dAtA[i:], m.LockId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.LockId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUnlockGResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUnlockGResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUnlockGResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgRedeemG) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRedeemG) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRedeemG) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DeadlineUnixNanos != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.DeadlineUnixNanos))
		i--
		dAtA[i] = 0x28
	}
	if len(m.MinGodOut) > 0 {
		i -= len(m.MinGodOut)
		copy(dAtA[i:], m.MinGodOut)
		i = encodeVarintTx(dAtA, i, uint64(len(m.MinGodOut)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Amount) > 0 {
		i -= len(m.Amount)
		copy(dAtA[i:], m.Amount)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Amount)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Beneficiary) > 0 {
		i -= len(m.Beneficiary)
		copy(dAtA[i:], m.Beneficiary)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Beneficiary)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRedeemGResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRedeemGResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRedeemGResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.GodOut) > 0 {
		i -= len(m.GodOut)
		copy(dAtA[i:], m.GodOut)
		i = encodeVarintTx(dAtA, i, uint64(len(m.GodOut)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDonateGod) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDonateGod) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDonateGod) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Amount) > 0 {
		i -= len(m.Amount)
		copy(dAtA[i:], m.Amount)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Amount)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDonateGodResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDonateGodResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDonateGodResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgClaimG) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgClaimGResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgTransferG) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Recipient)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Amount)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgTransferGResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgLockG) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.LockId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Amount)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgLockGResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUnlockG) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.LockId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUnlockGResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgRedeemG) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Beneficiary)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Amount)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.MinGodOut)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.DeadlineUnixNanos != 0 {
		n += 1 + sovTx(uint64(m.DeadlineUnixNanos))
	}
	return n
}

func (m *MsgRedeemGResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.GodOut)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgDonateGod) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Amount)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgDonateGodResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgClaimG) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgClaimG: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgClaimG: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgClaimGResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgClaimGResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgClaimGResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgTransferG) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgTransferG: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgTransferG: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Recipient", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Recipient = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgTransferGResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgTransferGResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgTransferGResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgLockG) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgLockG: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgLockG: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LockId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LockId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgLockGResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgLockGResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgLockGResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUnlockG) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUnlockG: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUnlockG: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LockId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LockId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUnlockGResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUnlockGResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUnlockGResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRedeemG) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRedeemG: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRedeemG: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Beneficiary", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Beneficiary = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinGodOut", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MinGodOut = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeadlineUnixNanos", wireType)
			}
			m.DeadlineUnixNanos = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DeadlineUnixNanos |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRedeemGResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRedeemGResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRedeemGResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GodOut", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GodOut = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDonateGod) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDonateGod: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDonateGod: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDonateGodResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDonateGodResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDonateGodResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
